config:
  domain: http://sales.wxdev.com:2086
  proxies: True
  code_address: http://36.155.98.104:49880/mtv/v1/smsMt/querySmsMt?pageNum=1&pageSize=20
  Super_administrator:
    username: super
    password: mgHg2022!11

proxies:
  http: 127.0.0.1:8888
  https: 127.0.0.1:8888


mysql:
  host: "127.1.0.1"
  user: "root"
  password: "root"
  port: 3306
  database: "mysql"

ssh:
  hostname:
  username:
  password:
  port:

log:
  name: interface
  level: INFO
  file_name: .log
  file_ok: True


