config:
  domain: https://mgw.lovev.com
  proxies: True

proxies:
  http: 127.0.0.1:8888
  https: 127.0.0.1:8888


mysql:
  host: "127.1.0.1"
  user: "root"
  password: "root"
  port: 3306
  database: "mysql"

ssh:
  hostname: "47.107.45.202"
  username: root
  password: nightfell1.
  port: 22

log:
  name: interface
  level: INFO
  file_name: .log
  file_ok: True


